services:
  chatgpt-on-wechat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatgpt-on-wechat
    restart: always
   
    volumes:
      - ./config.json:/app/a/config.json
