FROM python:3.10-slim

WORKDIR /app

LABEL maintainer="foo@bar.com"
ARG TZ='Asia/Shanghai'

ARG CHATBOT_VER

RUN echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm main contrib non-free non-free-firmware" > /etc/apt/sources.list && \
    echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm-updates main contrib non-free non-free-firmware" >> /etc/apt/sources.list && \
    echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian-security/ bookworm-security main contrib non-free non-free-firmware" >> /etc/apt/sources.list
# RUN echo /etc/apt/sources.list
# RUN sed -i 's/deb.debian.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list

RUN apt-get update \
    && apt-get install -y --no-install-recommends bash ffmpeg espeak libavcodec-extra git gcc g++ make \
    && pip install azure-cognitiveservices-speech \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/
COPY requirements-optional.txt /app/

RUN pip install --no-cache-dir -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/ \
    && pip install --no-cache-dir -r requirements-optional.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/

COPY . /app/

# ADD /entrypoint.sh /entrypoint.sh

# RUN chmod +x /entrypoint.sh \
#    && mkdir -p /home/noroot \
#    && groupadd -r noroot \
#    && useradd -r -g noroot -s /bin/bash -d /home/noroot noroot \
#    && chown -R noroot:noroot /home/noroot ${BUILD_PREFIX} /usr/local/lib

# 设置环境变量
ENV PYTHONUNBUFFERED=1

# ENTRYPOINT ["/entrypoint.sh"]
CMD ["python", "app.py"]