services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile.latest
    container_name: chatbot
    restart: always
    volumes:
      - ./config.json:/app/config.json
      - ./plugins/config.json:/app/plugins/config.json
    security_opt:
      - seccomp:unconfined
    environment:
      TZ: 'Asia/Shanghai'
      OPEN_AI_API_KEY: 'YOUR API KEY'
      MODEL: ''
      PROXY: ''
      SINGLE_CHAT_PREFIX: '["bot", "@bot"]'
      SINGLE_CHAT_REPLY_PREFIX: '"[bot] "'
      GROUP_CHAT_PREFIX: '["@bot"]'
      GROUP_NAME_WHITE_LIST: '["ALL_GROUP"]'
      IMAGE_CREATE_PREFIX: '["画"]'
      CONVERSATION_MAX_TOKENS: 2500
      SPEECH_RECOGNITION: 'False'
      CHARACTER_DESC: '你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'
      EXPIRES_IN_SECONDS: 3600
      USE_GLOBAL_PLUGIN_CONFIG: 'True'
      USE_LINKAI: 'False'
      LINKAI_API_KEY: ''
      LINKAI_APP_CODE: ''
   
