services:
  #chatgpt-on-wechat:
    #image: zhayujie/chatgpt-on-wechat
    #container_name: chatgpt-on-wechat
    #security_opt:
    # - seccomp:unconfined
  chatgpt-on-wechat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatgpt-on-wechat
    restart: always
   
    volumes:
      - ./config.json:/app/config.json
